export enum ServerKeys {
  EMAIL = "email",
  PASSWORD = "password",
  REMEMBER = "remember",
  EMAIL_VERIFIED = "emailVerified",
  USERNAME = "username",
  CREATED_AT = "createdAt",
  UPDATED_AT = "updatedAt",
  TAGS = "tags",
  USER_ID = "userId",
  TITLE = "title",
  CONTENT = "content",
  IMAGES = "images",
  FAVORITE = "favorite",
  PINNED = "pinned",
  NOTE_ID = "noteId",
  TOTAl = "total",
  SORT = "sort",
  PAGE = "page",
  LIMIT = "limit",
  SEARCH = "search",
  NOTES = "notes",
  BODY = "body",
}
